version: "3"
services:
  #Upload Service
  uploadsapp:
    image: migutak/upload:1.0.0
    container_name: uploadsapp
    restart: unless-stopped
    tty: true
    environment:
      MONGODB_CONNECTIONSTRING: mongodb://192.168.0.26:27017
    volumes:
      - /tmp/demands:/usr/src/app/uploads
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - app-network

  #Mongo Service
  mongo:
    image: mongo:4.0.4
    container_name: mongo
    restart: unless-stopped
    tty: true
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - /tmp/mongodb:/data/db
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
