apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-deployment
  labels:
    app: upload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload
  template:
    metadata:
      labels:
        app: upload
    spec:
      containers:
      - name: uploadsapp
        image: migutak/uploads:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - mountPath: /usr/src/app/uploads
          name: uploads-volume

      - name: mongo
        image: mongo:4.0.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - mountPath: /data/db
          name: mongodb-volume

      volumes:
      - name: uploads-volume
        hostPath:
          path: /tmp/demands
          type: DirectoryOrCreate
      - name: mongodb-volume
        hostPath:
          path: /tmp/mongodb
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: upload-service
spec:
  selector:
    app: upload
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30010